services:
  mongodb:
    image: 'mongo:8.0'
    environment:
      - 'MONGO_INITDB_DATABASE=car_marketplace'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
    ports:
      - '27018:27017'
    volumes:
      - 'mongo-data:/data/db'

volumes:
  mongo-data:
