spring.application.name=car-marketplace-api
server.port=8050
spring.mvc.problemdetails.enabled=true
spring.data.web.pageable.max-page-size=100
spring.data.mongodb.auto-index-creation=true
springdoc.override-with-generic-response=false
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.display-request-duration=true
springdoc.default-produces-media-type=application/json
